/**
 * Sync capcut-pipeline/manifest.json → Remotion constants + public asset paths.
 * Run: bun run video:sync
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const MANIFEST_PATH = join(ROOT, "apps", "video", "capcut-pipeline", "manifest.json")
const CONSTANTS_PATH = join(ROOT, "apps", "video", "src", "constants.ts")
const PUBLIC_ASSETS = join(ROOT, "apps", "video", "public", "assets")

interface Manifest {
  webUrl: string
  apiUrl: string
  runID: string
  orgId: string
  workspace: string | null
  invoices: { allow: string; escalate: string; blocked: string; upload: string }
  invoiceNumbers: { allow: string; escalate: string; upload: string }
}

function main() {
  if (!existsSync(MANIFEST_PATH)) {
    console.error("Missing manifest. Run: bun run video:seed")
    process.exit(1)
  }

  const manifest = JSON.parse(readFileSync(MANIFEST_PATH, "utf8")) as Manifest
  mkdirSync(PUBLIC_ASSETS, { recursive: true })

  const workspaceLabel = manifest.workspace ?? `Workspace ${manifest.runID.slice(-6)}`
  const runSuffix = manifest.runID

  const constants = `// AUTO-GENERATED by scripts/sync-video-manifest.ts — do not edit by hand
export const FPS = 30
export const WIDTH = 1920
export const HEIGHT = 1080

export const MASTER_DURATION_FRAMES = 4500
export const SOCIAL_DURATION_FRAMES = 1680

export const TRANSITION_FRAMES = 12

export const STAGING = {
  web: ${JSON.stringify(manifest.webUrl)},
  api: ${JSON.stringify(manifest.apiUrl)},
  orgId: ${JSON.stringify(manifest.orgId)},
  workspaceLabel: ${JSON.stringify(workspaceLabel)},
  runID: ${JSON.stringify(manifest.runID)},
}

export const INVOICES = {
  blocked: {
    id: ${JSON.stringify(manifest.invoices.blocked)},
    number: ${JSON.stringify(manifest.invoiceNumbers.allow)},
    vendor: ${JSON.stringify(`Acme Freight ${runSuffix}`)},
    amount: "2,500.00 USDC",
    wallet: "0x2222222222222222222222222222222222222222",
    approvedWallet: "0x1111111111111111111111111111111111111111",
    rules: ["invoice.duplicate", "wallet.changed"],
  },
  escalate: {
    id: ${JSON.stringify(manifest.invoices.escalate)},
    number: ${JSON.stringify(manifest.invoiceNumbers.escalate)},
    vendor: ${JSON.stringify(`Orbit Components ${runSuffix}`)},
    amount: "6,000.00 USDC",
    wallet: "0x3333333333333333333333333333333333333333",
    txHash: "0x408654cf843c82b9159d82a6452c29eb64784a7b481995602f2aded2f8dab2b8",
    rules: ["vendor.pending_onboarding", "amount.requires_review"],
  },
  ready: {
    id: ${JSON.stringify(manifest.invoices.allow)},
    number: ${JSON.stringify(manifest.invoiceNumbers.allow)},
    vendor: ${JSON.stringify(`Acme Freight ${runSuffix}`)},
    amount: "2,500.00 USDC",
    wallet: "0x1111111111111111111111111111111111111111",
  },
}

export const DASHBOARD = {
  pendingReview: 0,
  needsApproval: 0,
  blocked: 1,
  readyToPay: 1,
  totalProtected: "7,500.00 USDC",
  riskEvents: 6,
}

export const BRAND = {
  blue: "#0052ff",
  blueHover: "#578bfa",
  surface: "#ffffff",
  surfaceDark: "#0a0b0d",
  cardDark: "#282b31",
  text: "#0a0b0d",
  textMuted: "#5b616e",
  allow: "#00c853",
  block: "#ff3d00",
  escalate: "#ff9100",
  border: "rgba(91, 97, 110, 0.2)",
}

export const MASTER_SCENES = {
  coldOpen: { from: 0, duration: 280 },
  reveal: { from: 280, duration: 220 },
  dashboard: { from: 500, duration: 480 },
  inbox: { from: 980, duration: 280 },
  blockedHero: { from: 1260, duration: 1140 },
  escalate: { from: 2400, duration: 880 },
  readyFlash: { from: 3280, duration: 200 },
  audit: { from: 3480, duration: 500 },
  architecture: { from: 3980, duration: 340 },
  close: { from: 4320, duration: 288 },
} as const
`

  writeFileSync(CONSTANTS_PATH, constants)
  console.log(JSON.stringify({ ok: true, constantsPath: CONSTANTS_PATH, orgId: manifest.orgId }, null, 2))
}

main()
